# Generated by Django 4.2.11 on 2024-04-10 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('active', 'Активно'), ('reserved', 'Зарезервировано'), ('sold', 'Продано'), ('installment', 'Рассрочка'), ('barter', 'Бартер')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object', models.CharField(max_length=100)),
                ('floor', models.IntegerField()),
                ('square', models.IntegerField()),
                ('data', models.DateField(auto_now_add=True)),
                ('price', models.IntegerField()),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='apartments.status')),
            ],
        ),
    ]
