# Generated by Django 4.2.11 on 2024-04-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='status',
            field=models.CharField(choices=[('active', 'Активно'), ('reserved', 'Зарезервировано'), ('sold', 'Продано'), ('installment', 'Рассрочка'), ('barter', 'Бартер')], max_length=100),
        ),
    ]
