# Generated by Django 4.2.11 on 2024-04-10 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0002_alter_apartment_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
    ]
